name: Build Release APK and Create Draft Github Release
on:
  workflow_dispatch:
  push:
    branches: [ "snx" ]

jobs:
  build_and_release:
    name: Build Release APK and Create Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Write key
        run: |
          if [ ! -z "${{ secrets.KEY_STORE}}" ]; then
            echo '${{ secrets.LOCAL_PROPERTIES}}' >> local.properties
            wget ${{ secrets.KEY_STORE }}
            cp snxgram.jks app/snxgram.jks
          fi

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Get Tag Name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Release APK
        run: ./gradlew assembleRelease
        
      - name: Upload to Telegram          
        run: |
          mv app/build/outputs/apk/release/app-arm64-v8a-release.apk app/build/outputs/apk/release/nextplayer-${{ github.ref_name }}-arm64-v8a.apk
          export file="app/build/outputs/apk/release/nextplayer-${{ github.ref_name }}-arm64-v8a.apk"
          curl https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendDocument -X POST -F chat_id="1278600516" -F document="@$file"

      - name: Upload artifact nextplayer-arm64-v8a-debug.apk
        uses: actions/upload-artifact@v4
        with:
          name: nextplayer-arm64-v8a-release.apk
          path: ./app/build/outputs/apk/release/nextplayer-${{ github.ref_name }}-arm64-v8a.apk

      - name: Create Draft Release
        id: create_draft_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: app/build/outputs/apk/release/nextplayer-${{ github.ref_name }}-arm64-v8a.apk
          draft: true
          title: Release ${{ github.ref }}
